## 00. PyTorch Fundamentals

In [2]:
import torch
import numpy as np
import pandas as pd
import matplotlib as plt
print(torch.__version__)

2.8.0+cu126


## Introduction to Tensor
### Creating tensors

PyTorch tensors are created using `torch.Tensor()` = https://pytorch.org/docs/stable/tensors.html


In [3]:
#Scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim

0

In [5]:
# Get tensor back as Python int
scalar.item()

7

In [6]:
#Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [7]:
vector.ndim

1

In [8]:
vector.shape

torch.Size([2])

In [9]:
#MATRIX
MATRIX = torch.tensor([[7, 8], [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [10]:
MATRIX[1]

tensor([ 9, 10])

In [11]:
MATRIX.shape

torch.Size([2, 2])

In [12]:
# TENSOR
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR



tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [13]:
TENSOR.ndim

3

In [14]:
TENSOR.shape

torch.Size([1, 3, 3])

In [15]:
TENSOR[0][1][2]

tensor(9)

### Random tensors

Why random tensors?
Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

'Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers

Torch random tensors - https://docs.pytorch.org/docs/stable/generated/torch.rand.html

In [16]:
# Create a random tensor of size (3, 4)
random_tensor = torch.rand(1, 3, 4)
random_tensor

tensor([[[2.3168e-01, 3.8181e-01, 6.6197e-01, 5.0787e-01],
         [2.9224e-01, 5.2423e-01, 1.9420e-01, 7.5281e-04],
         [5.7913e-01, 9.9542e-01, 2.7409e-01, 5.2560e-02]]])

In [17]:
random_tensor.ndim

3

In [18]:
# Create a random tensor with similar shape to an image tensor

random_image_size_tensor = torch.rand(size=(224, 224, 3)) # height, width, color channels (R, G, B)

random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### Zeros and ones


In [19]:
# Create a stensor of all zeros

zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [20]:
# Create a stensor of all ones
ones = torch.zeros(size=(3, 4))
ones

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [21]:
ones.dtype

torch.float32

### Creating a range of tensors and tensors-like

In [22]:
# Use torch.range() and get deprecated message, use torch.arange()
one_to_ten = torch.arange(start = 1, end = 11, step = 1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [23]:
# Creating tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

**Note:** Tensor datatypes are one of the 3 big errors you'll run into with PyTorch & Deep learning.
1.   Tensors not right datatype
2.   Tensors not right shape
3.   Tensors not on the right device.

https://docs.pytorch.org/docs/stable/tensors.html

Precision in computing -
https://en.wikipedia.org/wiki/Precision_(computer_science)



In [24]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0], dtype=None, #What datatype is the tensor (e.g. float32 or float16)
                               device=None, #What device is your tensor on. CPU or CUDA or None
                               requires_grad=False) # Whether or not to track gradients with this tensors operations
float_32_tensor

tensor([3., 6., 9.])

In [25]:
float_32_tensor.dtype

torch.float32

In [26]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [27]:
float_16_tensor * float_32_tensor


tensor([ 9., 36., 81.])

In [28]:
int_32_tensor = torch.tensor([3, 6, 9,] , dtype = torch.long)
int_32_tensor

tensor([3, 6, 9])

In [29]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

### Getting information from tensors (tensor attributes)



1. Tensors not right datatype- To do get datatype from a tensor, can use tensor.dtype
2. Tensors not right shape- to get shape from a stensor, can use tensor.shape
3. Tensors not on the right device - to get device from a tensor, can use tensor.device



In [30]:
#Create a tensor
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.6451, 0.5458, 0.3329, 0.4395],
        [0.0556, 0.0761, 0.0312, 0.1357],
        [0.5304, 0.0171, 0.5145, 0.6094]])

In [31]:
some_tensor.size()

torch.Size([3, 4])

In [32]:
#Find out details about some tensor
print(some_tensor)
print(f"Datatype of tensor : {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.6451, 0.5458, 0.3329, 0.4395],
        [0.0556, 0.0761, 0.0312, 0.1357],
        [0.5304, 0.0171, 0.5145, 0.6094]])
Datatype of tensor : torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


### Manipulating Tensors (tensor operations)

Tensor operations include:
* Addition
* Subtraction
* Multiplication (elememt-wise)
* Divsioion
* Matrix multiplication

In [33]:
# Create a tensor and add 10 to it
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [34]:
# Multiply tensor by 10
tensor * 10


tensor([10, 20, 30])

In [35]:
tensor

tensor([1, 2, 3])

In [36]:
# Subtract 10
tensor - 10

tensor([-9, -8, -7])

In [37]:
# Try out PyTorch in-built functions
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [38]:
torch.add(tensor, 10)

tensor([11, 12, 13])

### Matrix multiplication

Two main ways of performing multiplication in neural networks and deep learning:

1.  Element-wise multiplication
2.  Matrix multiplication (dot product)

More information on multiplying matrices – https://www.mathsisfun.com/algebra/matrix-multiplying.html

There are two main rules that performing matrix multiplication needs to satisfy:


1.   The **inner dimensions** must watch:
* `(3, 2) @ (3, 2)` won't work
* `(2, 3) @ (3, 2)` will work
* `(3, 2) @ (2, 3)` will work
2. The resulting matrix has te shape of the **outer dimensions**:
* `(2, 3) @ (3, 2)` -> (2, 2)
* `(3, 2) @ (2, 3)`-> (3, 3)




In [39]:
# Element wise multiplication
print(tensor, "*", tensor)
print(f"Equals: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [41]:
# Matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [42]:
# Matrix multiplication by hand
1 * 1 + 2*2 + 3*3

14

In [45]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]

print(value)

tensor(14)
CPU times: user 2.21 ms, sys: 23 µs, total: 2.23 ms
Wall time: 3.24 ms


In [47]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 824 µs, sys: 0 ns, total: 824 µs
Wall time: 883 µs


tensor(14)

### One of the most common errors with deep learning: Shape errors

In [49]:
# Shapes for matrix multiplication
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])
tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]])

torch.mm(tensor_A, tensor_B) # torch.mm is the same as torch.matmul( it's an alias for matmul)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [50]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

To Fix our tensor shape issues, we can manipulate the shape of one of our tensors using a transpose.
A ***transpose*** switches the axes or dimensions of a given tensor.

In [52]:
tensor_B.T,

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),)

In [54]:
tensor_B.T.shape

torch.Size([2, 3])

In [56]:
# The matrix multiplication operation works when tensor_B is transposed
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}")
print(f"New shapes: tensor_A = {tensor_A.shape} (same shape as above), tensor_B.T = {tensor_B.T.shape}")
print(f"Multiplying: {tensor_A.shape} @ {tensor_B.T.shape} <- inner dimensions must match")
print("Output:\n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output)
print(f"\nOutput shape: {output.shape}")


Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])
New shapes: tensor_A = torch.Size([3, 2]) (same shape as above), tensor_B.T = torch.Size([2, 3])
Multiplying: torch.Size([3, 2]) @ torch.Size([2, 3]) <- inner dimensions must match
Output:

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

Output shape: torch.Size([3, 3])


In [ ]:
## Finding the min, max, mean, sum, etc (tensor aggregation)

In [57]:
# Create a tensor
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [59]:
# Find the min
torch.min(x), x.min()

(tensor(0), tensor(0))

In [60]:
# Find the max
torch.max(x), x.max()

(tensor(90), tensor(90))

In [62]:
# Find the mean - note: the torch.mean() function requires a tensor of float32 datatype to work
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [63]:
# Find the sum
torch.sum(x), x.sum()

(tensor(450), tensor(450))

### Finding the positional min and max

In [64]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [65]:
# Find the position in tensor that has the minimum value with argmin()
# -> returns index position of target tensor where the minimum value occurs
x.argmin()


tensor(0)

In [66]:
x[0]

tensor(0)

In [67]:
# Find the position in tensor that has the maximum value with argmax()
x.argmax()


tensor(9)

In [68]:
x[9]

tensor(90)

### Reshaping, stacking, squeezing and unsqueezing tensors

* Reshaping – reshapes an input tensor to a defined shape

* View – return a view of an input tensor of certain shape but keep the same memory as the original tensor

* Stacking – combine multiple tensors on top of each other (vstack) or side by side (hstack)

* Squeeze – removes all 1 dimensions from a tensor

* Unsqueeze – add a 1 dimension to a target tensor

* Permute – return a view of the input with dimensions permuted (swapped) in a certain way

In [69]:
# Let's create a tensor
import torch
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [72]:
# Add an extra dimension
x_reshaped = x.reshape(1, 9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))